title: No-Knives Cooking
description: Knife-free cooking, adaptations, and gentle routines.
theme: minima

# Show these pages as top navigation
header_pages:
  - index.md
  - journal.md
  - recipes.md
  - aids-and-adaptations.md
  - ocd.md
  - intrusive-thoughts.md
  - grounding.md
  - about.md
